project:
  type: website
  title: "Lectures - Model Predictive Control"
  output-dir: _site

website:
  title: "Lectures - Model Predictive Control"
  description: "Lectures and tutorials on Model Predictive Control (MPC)"
  site-url: https://phatcvo.github.io/Lec-MPC/
  repo-url: https://github.com/phatcvo/Lec-MPC
  repo-actions: [edit, issue]
  navbar:
    left:
      - text: Main Site
        href: https://phatcvo.github.io/
      - text: Courses
        menu:
          - text: Deep RL
            href: https://phatcvo.github.io/Lec-DRL/
          - text: MPC
            href: https://phatcvo.github.io/Lec-MPC/
          - text: Safe-Optimal
            href: https://phatcvo.github.io/Safe-Optimal-Control/
      - text: Course
        menu:
          - text: Course Home
            href: index.qmd
          - text: Posts Index
            href: index.qmd#lectures
          - text: "---"
          - text: Core Topics
          - text: Linear MPC
            href: posts/Linear-Model-Predictive-Control.qmd
          - text: Nonlinear MPC
            href: posts/Nominal-Nonlinear-Model-Predictive-Control.qmd
          - text: iLQR & DDP
            href: posts/Iterative-Linear-Quadratic-Regulator-and-Differential-Dynamic-PRogramming.qmd
          - text: CBF Integration
            href: posts/Model-Predictive-Control-with-discrete-time-Control-Barrier-Functions.qmd
          - text: Quadrotor MPC
            href: posts/MPC-for-Quadrotor.qmd
      - text: Resources
        menu:
          - text: GitHub Repo
            href: https://github.com/phatcvo/Lec-MPC
          - text: Deep RL Course
            href: https://phatcvo.github.io/Lec-DRL/
          - text: Safe-Optimal Survey
            href: https://phatcvo.github.io/Safe-Optimal-Control/
    right:
      - icon: github
        href: https://github.com/phatcvo/Lec-MPC
        aria-label: GitHub
  
  sidebar:
    - title: "Lectures"
      contents:
        - index.qmd
        - section: "Posts"
          contents:
            - posts/Iterative-Linear-Quadratic-Regulator-and-Differential-Dynamic-PRogramming.qmd
            - posts/LPV-MPP-MCP-for-racing.qmd
            - posts/Learning-MPC-for-Racing.qmd
            - posts/Linear-Model-Predictive-Control.qmd
            - posts/MPC-for-Quadrotor.qmd
            - posts/Model-Predictive-Control-with-discrete-time-Control-Barrier-Functions.qmd
            - posts/Nominal-Nonlinear-Model-Predictive-Control.qmd

format:
  html:
    theme:
      light: cosmo
      dark: cosmo
    css: [assets/theme-sync.scss, assets/custom.scss]
    toc: true
    toc-location: right
    code-fold: true
    code-tools: true
    highlight-style: github
    number-sections: false
    reference-location: margin
    citation-location: margin
    html-math-method: mathjax
    bibliography: 
      - assets/DeepLearning.bib
      - assets/ReinforcementLearning.bib
    csl: assets/apalike.csl

execute:
  freeze: auto
  echo: false
  warning: false
  message: false
