project:
  type: website
  title: "Lectures - Model Predictive Control"
  output-dir: _site

website:
  title: "Lectures - Model Predictive Control"
  description: "Lectures and tutorials on Model Predictive Control (MPC)"
  site-url: https://phatcvo.github.io/Lec-MPC/
  repo-url: https://github.com/phatcvo/Lec-MPC
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: https://phatcvo.github.io/
        text: Home
      - href: https://phatcvo.github.io/Lec-MPC/
        text: Posts
  
  sidebar:
    - title: "Lectures"
      contents:
        - index.qmd
        - section: "Posts"
          contents:
            - posts/Iterative-Linear-Quadratic-Regulator-and-Differential-Dynamic-PRogramming.qmd
            - posts/LPV-MPP-MCP-for-racing.qmd
            - posts/Learning-MPC-for-Racing.qmd
            - posts/Linear-Model-Predictive-Control.qmd
            - posts/MPC-for-Quadrotor.qmd
            - posts/Model-Predictive-Control-with-discrete-time-Control-Barrier-Functions.qmd
            - posts/Nominal-Nonlinear-Model-Predictive-Control.qmd

format:
  html:
    theme: cosmo
    css: assets/custom.scss
    toc: true
    toc-location: right
    code-fold: true
    code-tools: true
    highlight-style: github
    number-sections: false
    reference-location: margin
    citation-location: margin
    html-math-method: mathjax
    bibliography: 
      - assets/DeepLearning.bib
      - assets/ReinforcementLearning.bib
    csl: assets/apalike.csl

execute:
  freeze: auto
  echo: false
  warning: false
  message: false
